name: Java Test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: adopt # or temurin

      - name: Build with Maven
        run: mvn package --batch-mode --no-transfer-progress

      - name: Run tests
        run: mvn test --batch-mode --no-transfer-progress